spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zzz_imchat?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
jwt:
  secret-key: qwertyuiopasdfghjklzxcvbnmzzzlew
  # token过期时间，单位毫秒，默认7天
  expiration: 604800000
  token-name: Authorization
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzzlew.zzzimserver.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
    zzzlew:
    zzzimserver:
      mapper: debug
      server: info
      controller: info
